### ISSUE TITLE
artistnames and albumname not found 

### ISSUE THREAD

**Issue by rakshith111** [MAX-dev2020/Spotify-automate#1]
`Traceback (most recent call last):
  File "C:\Users\Aorus\Visual Studios\spotify\Spotify-automate\spotifymain.py", line 156, in <module>
    search_song["tracks"]["items"][i]["artists"][j]["name"] .split()).replace('.', '')
NameError: name 'search_song' is not defined`
 pls fix

**Comment by MAX-dev2020** [comment]
1. fixed the error
2. changed the searching algo. Now the algo doesn't take duplicates if the file has proper meta data.
