### ISSUE TITLE
function

### ISSUE THREAD

**Issue by troicc** [MAX-dev2020/Spotify-automate#2]
If I understand your program right, it is just used to sync the songs that can be listened on the spotify. If I want to synchronize the local songs that can not be searched on the spotify(like no copyright or not the right version), then the program can not help me with that.

**Comment by MAX-dev2020** [comment]
This program was built to automate the searching and adding of songs to the Spotify playlist using the local songs on your computer. It only adds songs which are available on Spotify. If you want to add songs which are not on Spotify then you have to be an artist to do, if that's what you're asking for.

**Comment by MAX-dev2020** [comment]
> If I understand your program right, it is just used to sync the songs that can be listened on the spotify. If I want to synchronize the local songs that can not be searched on the spotify(like no copyright or not the right version), then the program can not help me with that.


This program was built to automate the searching and adding of songs to the Spotify playlist using the local songs on your computer. It only adds songs which are available on Spotify. If you want to add songs which are not on Spotify then you have to be an artist to do, if that's what you're asking for.

**Comment by troicc** [comment]
Gotcha. Thanks.
